### ISSUE TITLE
EWS-JAVA-API: java.lang.VerifyError: microsoft/exchange/webservices/data/ExchangeServiceBase

### ISSUE THREAD

**Issue by nomanuddin** [faisons-git/EWS-For-Android#3]
I have used your code and instructions and I faced following issue:

`java.lang.VerifyError: microsoft/exchange/webservices/data/ExchangeServiceBase
                                                                 at culha.roomdispaly.MainActivity.onCreate(MainActivity.java:125)
                                                                 at android.app.Activity.performCreate(Activity.java:5411)
                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2270)
                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2396)
                                                                 at android.app.ActivityThread.access$800(ActivityThread.java:139)
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1293)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                 at android.os.Looper.loop(Looper.java:149)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5257)
                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                 at java.lang.reflect.Method.invoke(Method.java:515)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
                                                                 at dalvik.system.NativeStart.main(Native Method)`

Further issue details are on this link: **[http://stackoverflow.com/questions/36942623/ews-java-api-java-lang-verifyerror-microsoft-exchange-webservices-data-exchang](url)**

any hint?? 

thanks in advance

**Comment by D-Blazer** [comment]
I am running into the same issue when i instantiate:
`ExchangeService service = new ExchangeService();`

has this problem been solved, if so how, if not, i would appreciate any hint.

Thanks in advance,
D. Blazer

**Comment by faisons** [comment]
Hi, I couldn,t able to reproduce this error on my system. Please check the
above lines of log for actual reason of the verify error.
Thanks
Faison
